# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

import sphinx_rtd_theme
from recommonmark.parser import CommonMarkParser

# -- Project information -----------------------------------------------------

project = u'CronApi'
copyright = u'2018, Equipe Cronapp'
author = u'Equipe Cronapp'

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ['.rst', '.md']
source_parsers = {
    '.md': CommonMarkParser,
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = u'pt'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store', '**/*-ext.rst', '**/*-header.rst', '**/*-footer.rst', 'README.md']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_logo = 'img/logo.svg'
html_theme_options = {
    'logo_only': True,
    'display_version': False,
}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'CronApidoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {

}

# Grouping the document tree into LaTeX files. List of tuples

latex_documents = [
    ('index', 'CronApi.tex', u'CronApi Documentation',
     u'Equipe CronApp', 'manual'),
]


# -- Options for manual page output ------------------------------------------

man_pages = [
    ('index', 'cronapi', u'CronApi Documentation',
     [u'Equipe CronApp'], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'CronApi', u'CronApi Documentation',
     author, 'CronApi', 'One line description of project.',
     'Miscellaneous'),
]

def setup(app):
    app.add_stylesheet('css/custom.css')